#   (                                     )  (     
#   )\ )   )                 )         ( /(  )\ )  
#  (()/(( /(              ( /(     (   )\())(()/(  
#   /(_))\()) (  (  `  )  )\()) (  )( ((_)\  /(_)) 
#  (_))((_)\  )\ )\ /(/( ((_)\  )\(()\  ((_)(_))   
#  | _ \ |(_)((_|(_|(_)_\| |(_)((_)((_)/ _ \/ __|  
#  |  _/ ' \/ _ (_-< '_ \) ' \/ _ \ '_| (_) \__ \  
#  |_| |_||_\___/__/ .__/|_||_\___/_|  \___/|___/  
#                |_|                                                                                                                         ███    ███                         
#

[window]
opacity = 0.75
[colors]
[colors.primary]
background = "#1e1e2e"
foreground = "#cdd6f4"

[colors.normal]
black   = "#1e1e2e"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#cba6f7"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#cdd6f4"

[colors.bright]
black   = "#585b70"
red     = "#f38ba8"
green   = "#a6e3a1"
yellow  = "#f9e2af"
blue    = "#cba6f7"
magenta = "#f5c2e7"
cyan    = "#94e2d5"
white   = "#cdd6f4"

[colors.cursor]
text   = "#1e1e2e"
cursor = "#cba6f7"

#      )                                     
#   ( /(  (  (               )        )      
#   )\()) )\ )\ )  (      ( /(     ( /(      
#  ((_)\ ((_|()/(  )\  (  )\()) (  )\()) (   
#    ((_) _  ((_))((_) )\((_)\  )\((_)\  )\  
#   / _ \| | _| |_ | |((_) |(_)((_) |(_)((_) 
#  | (_) | / _` | || / _ \ '_ Y _ \ '_ Y _ \ 
#   \___/|_\__,_|\__/\___/_.__|___/_.__|___/ 
#                                            
#  25-01-26
