#   (                                     )  (     
#   )\ )   )                 )         ( /(  )\ )  
#  (()/(( /(              ( /(     (   )\())(()/(  
#   /(_))\()) (  (  `  )  )\()) (  )( ((_)\  /(_)) 
#  (_))((_)\  )\ )\ /(/( ((_)\  )\(()\  ((_)(_))   
#  | _ \ |(_)((_|(_|(_)_\| |(_)((_)((_)/ _ \/ __|  
#  |  _/ ' \/ _ (_-< '_ \) ' \/ _ \ '_| (_) \__ \  
#  |_| |_||_\___/__/ .__/|_||_\___/_|  \___/|___/  
#                  |_|                                                                                                                         ███    ███                         
#
#  Based on the Matrix Base16 colorscheme
#
#


accent = "#cba6f7"
active_border_color = "#cba6f7"
active_tab_background = "#cba6f7"
cursor = "#cba6f7"
foreground = "#cdd6f4"
background = "#1e1e2e"
selection_foreground = "#cdd6f4"
selection_background = "#45475a"

color0 = "#1e1e2e"
color1 = "#f38ba8"
color2 = "#a6e3a1"
color3 = "#f9e2af"
color4 = "#cba6f7"
color5 = "#f5c2e7"
color6 = "#94e2d5"
color7 = "#cdd6f4"
color8 = "#585b70"
color9 = "#f38ba8"
color10 = "#a6e3a1"
color11 = "#f9e2af"
color12 = "#cba6f7"
color13 = "#f5c2e7"
color14 = "#94e2d5"
color15 = "#cdd6f4"


#      )                                     
#   ( /(  (  (               )        )      
#   )\()) )\ )\ )  (      ( /(     ( /(      
#  ((_)\ ((_|()/(  )\  (  )\()) (  )\()) (   
#    ((_) _  ((_))((_) )\((_)\  )\((_)\  )\  
#   / _ \| | _| |_ | |((_) |(_)((_) |(_)((_) 
#  | (_) | / _` | || / _ \ '_ Y _ \ '_ Y _ \ 
#   \___/|_\__,_|\__/\___/_.__|___/_.__|___/ 
#                                            
#  25-01-26
